# Tiedonkäsittely Pythonilla (4 op)
### Seuraavan osion tekijä: Roni Pihajoki
Lisätään tarvittavat kirjastot & datasetti käyttöön

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df_roni = pd.read_csv('WorkPlaceSatisfactionSurveyData.csv', encoding='utf-8')

## Miltä datasetti näyttää, mitä se pitää sisällään ja montako riviä/saraketta siinä on
Ensin on tuloste rivien & sarakkeiden määristä <br>
Sen jälkeen on tuloste taulukon kolmesta ensimmäisestä rivistä <br>
Tästä näemme sarakeotsikot & esimerkit arvoista, joita taulukko sisältää <br>
Tämän pohjalta saamme ajatuksen, mitä dataa meillä on ja mitä kaikkea voimme sillä tehdä <br>

In [12]:
print("Rivien lukumäärä: ",df_roni.shape[0])
print("Sarakkeiden lukumäärä: ",df_roni.shape[1])
print()
df_roni.head(3)

Rivien lukumäärä:  82
Sarakkeiden lukumäärä:  16

,number,gender,age,family,education,years_of_service,salary,sat_management,sat_colleques,sat_workingEnvironment,sat_salary,sat_tasks,holidayCabin,gym,muscleCare,healtcare
0,1,1,38,1,1.0,22.0,3587,3,3.0,3,3,3,NaN,NaN,NaN,NaN
1,2,1,29,2,2.0,10.0,2963,1,5.0,2,1,3,NaN,NaN,NaN,NaN
2,3,1,30,1,1.0,7.0,1989,3,4.0,1,1,3,NaN,NaN,NaN,1.0

## Datan käsittely
Minulle tuli seuraavat sarakkeet käsiteltäväksi:
- Education (Sarake E) // Luokkamuuttuja
- Salary (Sarake G) // Numeerinen muuttuja

Taustamuuttujat eli Sat_sarakkeet ovat "tyytyväisyys" sarakkeita<br>
- sat_management // Tämä kertoo kuinka tyytyväisiä johdosta ollaan
- sat_colleques // Tämä kertoo kuinka tyytyväisiä kolleegoista ollaan
- sat_workingEnvironment // Tämä kertoo kuinka tyytyväisiä työympäristöön ollaan
- sat_salary // Tämä kertoo kuinka tyytyväisiä palkkaan ollaan
- sat_tasks // Tämä kertoo kuinka tyytyväisiä työtehtäviin ollaan

Projektissa on ideana että käsitellään ensin 2 saatua saraketta (luokkamuuttuja & numeerinen muuttuja)<br>
Sitten kun niiden kanssa on analysointi valmista, aletaan tutkimaan taustamuuttujien kanssa<br>
Yhteensä tehdään siis 11 yhdistelmästä ja 2 erillisellä muuttuja tyypillä analysointia<br>

## Taulukon siistiminen
Poistetaan taulukosta meille turhat sarakkeet käyttäen .drop komentoa<br>
1. Tulostetaan tämän hetkisten sarakkeiden nimet
2. Poistetaan sieltä 4 viimeistä saraketta, joita me emme käytä
3. Tulostetaan 3 ensimmäistä riviä uudestaan, josta näemme että sarakkeet on poistettu oikein

In [13]:
df_roni.columns

Index(['number', 'gender', 'age', 'family', 'education', 'years_of_service',
       'salary', 'sat_management', 'sat_colleques', 'sat_workingEnvironment',
       'sat_salary', 'sat_tasks', 'holidayCabin', 'gym', 'muscleCare',
       'healtcare'],
      dtype='str')

In [14]:
df_roni = df_roni.drop(columns=['holidayCabin', 'gym', 'muscleCare', 'healtcare'])

In [15]:
df_roni.head(3)

,number,gender,age,family,education,years_of_service,salary,sat_management,sat_colleques,sat_workingEnvironment,sat_salary,sat_tasks
0,1,1,38,1,1.0,22.0,3587,3,3.0,3,3,3
1,2,1,29,2,2.0,10.0,2963,1,5.0,2,1,3
2,3,1,30,1,1.0,7.0,1989,3,4.0,1,1,3