## Let's join couple of Series structures together

=> Hence, we move towards dataframes

In [1]:
import pandas as pd

In [2]:
series1 = pd.Series([1,2,3,4], index=['a', 'b', 'c', 'd'])
series1.name = "A"
series1.index.name = "Index_S1"

series2 = pd.Series([1,2,3,4])   # So this is without user given index -> index is 0,1,2,3,...
series2.name="B"
series2.index.name="Index_S2"

In [3]:
series1

Index_S1
a    1
b    2
c    3
d    4
Name: A, dtype: int64

In [4]:
series2

Index_S2
0    1
1    2
2    3
3    4
Name: B, dtype: int64

Let's join series1 ja series2 together using dictionary approach (https://thispointer.com/python-6-different-ways-to-create-dictionaries/)

In [5]:
# Tämä on alla esitetylle toinen tapa, eli tapa alustaa dataframe dictionary avulla...
my_dict=dict(s1=series1, s2=series2)

In [6]:
my_dict

{'s1': Index_S1
 a    1
 b    2
 c    3
 d    4
 Name: A, dtype: int64,
 's2': Index_S2
 0    1
 1    2
 2    3
 3    4
 Name: B, dtype: int64}

In [7]:
my_dict["s1"]

Index_S1
a    1
b    2
c    3
d    4
Name: A, dtype: int64

In [8]:
type(my_dict["s1"])

pandas.core.series.Series

## Create DataFrame
#### Case: Indexes are not the same

In [9]:
df=pd.DataFrame(my_dict)

In [10]:
df

    s1   s2
a  1.0  NaN
b  2.0  NaN
c  3.0  NaN
d  4.0  NaN
0  NaN  1.0
1  NaN  2.0
2  NaN  3.0
3  NaN  4.0

In [11]:
df['s1']

a    1.0
b    2.0
c    3.0
d    4.0
0    NaN
1    NaN
2    NaN
3    NaN
Name: s1, dtype: float64

In [12]:
df['s1']

a    1.0
b    2.0
c    3.0
d    4.0
0    NaN
1    NaN
2    NaN
3    NaN
Name: s1, dtype: float64

In [13]:
df[['s1', 's2']]

    s1   s2
a  1.0  NaN
b  2.0  NaN
c  3.0  NaN
d  4.0  NaN
0  NaN  1.0
1  NaN  2.0
2  NaN  3.0
3  NaN  4.0

In [14]:
type(df[['s1', 's2']])

pandas.core.frame.DataFrame

Let's check how DataFrame's Index look like - so it also has one :)

In [15]:
df.index  # So it is combined from those two from series1 and series2

Index(['a', 'b', 'c', 'd', 0, 1, 2, 3], dtype='object')

#### Case: indexes are the same

In [16]:
# Note! We are overriding the previous series1 and series2

series1 = pd.Series([1,2,3,4])
series1.name = "A"
series1.index.name = "Index_S1"

series2 = pd.Series([5,6,7,8])   
series2.name="B"
series2.index.name="Index_S2"

In [17]:
series1

Index_S1
0    1
1    2
2    3
3    4
Name: A, dtype: int64

In [18]:
series2

Index_S2
0    5
1    6
2    7
3    8
Name: B, dtype: int64

In [19]:
df=pd.DataFrame(dict(s1=series1, s2=series2))

In [20]:
df  # The same index

   s1  s2
0   1   5
1   2   6
2   3   7
3   4   8

In [21]:
type(df.index)

pandas.core.indexes.range.RangeIndex

In [22]:
df.columns  # DataFrame has also column index

Index(['s1', 's2'], dtype='object')

In [23]:
df

   s1  s2
0   1   5
1   2   6
2   3   7
3   4   8